window:
  dimensions:
    columns: 80
    lines: 24
  padding:
    x: 2
    y: 2
  decorations: full
scrolling:
  history: 10000
  multiplier: 3
  faux_multiplier: 3
  auto_scroll: false
tabspaces: 8
font:
  normal:
    family: FuraCode Nerd Font Mono Regular 
  size: 16
  offset:
    x: 0
    y: 1 
  glyph_offset:
    x: 0
    y: 1
render_timer: false
draw_bold_text_with_bright_colors: true
colors:
  primary:
    background: '0x2E3440'
    foreground: '0xD8DEE9'
  cursor:
    text: '0x2E3440'
    cursor: '0xD8DEE9'
  normal:
    black: '0x3B4252'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x88C0D0'
    white: '0xE5E9F0'
  bright:
    black: '0x4C566A'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x8FBCBB'
    white: '0xECEFF4'
visual_bell:
  animation: EaseOutExpo
  duration: 0
background_opacity: 1.0
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: false
  url:
    launcher: xdg-open
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: false
dynamic_title: true
cursor:
  style: Block
  unfocused_hollow: true
live_config_reload: true

