#!/usr/bin/env bash

export YOUTUBE_DL_AUDIO_OPTS="--extract-audio --audio-format mp3 --audio-quality 1 --max-filesize 10m --ignore-errors"

function youtube-dl-audio-playlist-with-title() {

        export TITLE=$1 
        export PLAYLIST_URL=$2

        set -o xtrace
        
        youtube-dl ${PLAYLIST_URL} \
                -o "~/Audio/%(playlist_title)s/${TITLE}/%(title)s - %(upload_date)s.%(ext)s" \
                --match-title ${TITLE} \
                $(echo ${YOUTUBE_DL_AUDIO_OPTS})
}


function youtube-dl-install {
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
}

function youtube-dl-audio-playlist-sample() {

        export NUMBER=$1
        export PLAYLIST_URL=$2

        set -o xtrace
        
        youtube-dl $(echo ${PLAYLIST_URL}) \
                -o "~/Audio/%(playlist_title)s/SAMPLE/%(title)s - %(upload_date)s.%(ext)s" \
                --playlist-random --max-downloads $(echo ${NUMBER}) \
                $(echo ${YOUTUBE_DL_AUDIO_OPTS})
}
