#!/usr/bin/env bash

muttfile=~/.muttrc

function washmutt() {
        set -o xtrace
        for field in 'smtp_url' 'folder' 'realname' 'from' 'spoolfile'; do
                sed -i "/${field}/d" ${muttfile}
        done
}

function protonmutt() {

        if ! [ $# -ge 3 ]; then
                {
                        echo "USAGE: protonmutt <PROTONMAIL_USERNAME> <MUTT_REALNAME> <MUTT_FROM>"
                        return
                }
        fi

        echo -n "ProtonMail Password:"
        read -s pass

        set -o xtrace

        bridge_out=$(hydroxide auth ${1} <<< printf ${pass})
        bridge_pass=$(echo ${bridge_out} | awk 'NF>1{print $NF}')

        washmutt

        echo "set folder=\"imap://${1}:${bridge_pass}@127.0.0.1:1143\"" >>${muttfile}
        echo "set smtp_url=\"smtp://${1}:${bridge_pass}@127.0.0.1:1025\"" >>${muttfile}
        echo "set spoolfile=\"+INBOX\"" >>${muttfile}
        echo "set realname=\"${2}\"" >>${muttfile}
        echo "set from=\"${3}\"" >>${muttfile}

        hydroxide smtp &
        hydroxide imap &

        echo "SUCCESS. Ready for mutt login."
        read

        mutt -F ${muttfile}
}
