#!/usr/bin/env bash

function nordelementary() {
        gsettings set io.elementary.terminal.settings foreground '#D8DEE9'
        gsettings set io.elementary.terminal.settings background '#2E3440'
        gsettings set io.elementary.terminal.settings palette '#3B4252:#BF616A:#A3BE8C:#EBCB8B:#81A1C1:#B48EAD:#88C0D0:#E5E9F0:#4C566A:#BF616A:#A3BE8C:#EBCB8B:#81A1C1:#B48EAD:#8FBCBB:#ECEFF4'
}

function trimelementary() {
        gsettings set io.elementary.terminal.settings tab-bar-behavior 'Never Show Tabs'
        gsettings set io.elementary.terminal.settings remember-tabs false
        gsettings set io.elementary.terminal.settings save-exited-tabs false
        gsettings set io.elementary.terminal.settings alt-changes-tab false
        gsettings set io.elementary.terminal.settings follow-last-tab false
}

function fontelementary() {
        gsettings set io.elementary.terminal.settings font # '<SOURCE CODE PRO>'

        gsettings set org.gnome.desktop.interface font-name  # '<SOURCE CODE PRO>'
        gsettings set org.gnome.desktop.interface document-font-name  # '<SOURCE CODE PRO>'
        gsettings set org.gnome.desktop.interface monospace-font-name  # '<SOURCE CODE PRO>'
}
