#!/usr/bin/env bash

function _git_repo_name() {
        echo $(
                cd ${1}
                basename $(git rev-parse --show-toplevel)
        )
}

function makedot() {
        (
                cd $1
                git ls-files
        ) |
                while read f; do {
                        ORIG="${1}/${f}"
                        DEST="${HOME}/${f}"
                        DEST_DIR=$(dirname $DEST)
                        if ! [[ -d $DEST_DIR ]]; then
                                {
                                        mkdir -p $DEST_DIR
                                }
                        fi
                        cp -r $ORIG $DEST
                }; done
}

function takedot() {
        (
                cd $1
                git ls-files
        ) |
                while read f; do {
                        ORIG="${HOME}/${f}"
                        DEST="${1}/${f}"
                        if [ -f $ORIG ]; then 
                                {
                                        cp -r $ORIG $DEST
                                }
                        fi
                }; done
}
