#!/usr/bin/env bash

function _git_repo_name() {
        echo $(
                cd ${1}
                basename $(git rev-parse --show-toplevel)
        )
}

function git-make-dot() {
        (
                cd $1
                git ls-files
        ) |
                while read f; do {
                        ORIG="${1}/${f}"
                        DEST="${HOME}/${f}"
                        DEST_DIR=$(dirname $DEST)
                        if ! [[ -d $DEST_DIR ]]; then
                                {
                                        mkdir -p $DEST_DIR
                                }
                        fi
                        cp -r $ORIG $DEST
                }; done
}

function git-take-dot() {
        (
                cd $1
                git ls-files
        ) |
                while read f; do {
                        ORIG="${HOME}/${f}"
                        DEST="${1}/${f}"
                        if [ -f $ORIG ]; then 
                                {
                                        cp -r $ORIG $DEST
                                }
                        fi
                }; done
}


function git-rewrite-author() {

        if [ "$#" -ne 3 ]; then { 
                echo "USAGE: git-rewrite-author <OLD_EMAIL> <CORRECT_NAME>
                <CORRECT_EMAIL>"
                return
        } fi


        git filter-branch --env-filter "
        OLD_EMAIL=${1}
        CORRECT_NAME=${2}
        CORRECT_EMAIL=${3}" + '
        if [ $GIT_COMMITTER_EMAIL = $OLD_EMAIL ]
        then
        export GIT_COMMITTER_NAME=$CORRECT_NAME
        export GIT_COMMITTER_EMAIL=$CORRECT_EMAIL
        fi
        if [ $GIT_AUTHOR_EMAIL = $OLD_EMAIL ]
        then
        export GIT_AUTHOR_NAME=$CORRECT_NAME
        export GIT_AUTHOR_EMAIL=$CORRECT_EMAIL
        fi
        ' --tag-name-filter cat -- --branches --tags
}
